safe: true
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'serve.sh', 'article.png', 'sync.sh', 'LICENSE', 'private']
baseurl: /paper-now
imports:
    - http://localhost:8000/research-article/research-article.html
theme: http://localhost:8000/paper-themes/paper-now/
collections:
    figures:
        output: true
        title: 'Figures'
    tables:
        output: true
        title: 'Tables'
    sections:
        output: true
